### ISSUE TITLE
osd 4.12 support

### ISSUE THREAD

**Issue by MStokluska** [3scale-ops/marin3r#141]
Following notice that OSD 4.12 will require k8s 1.25 we need to ensure that anything on this list is addressed before 4.12 release: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

**Comment by roivaz** [comment]
Keep open until a new release with these changes is published

**Comment by roivaz** [comment]
@MStokluska  image quay.io/3scale/marin3r:v0.11.0-alpha.1 is available for testing. It includes the changes to address api deprecations in k8s 1.25.

**Comment by roivaz** [comment]
[Release v0.11.0](https://github.com/3scale-ops/marin3r/releases/tag/v0.11.0) is out.
