### ISSUE TITLE
Slow reconcilliation of EnvoyDeployment and DiscoveryService

### ISSUE THREAD

**Issue by pehala** [3scale-ops/marin3r#164]
I observed that it takes a while for `EnvoyDeployment` and `DiscoveryService` resources to get ready (e.g. deployment is created and the pod is running), definitely much longer than it should have. It does eventually get created, and for one instance, it is not a problem. However, for multiple resources created at the same time, it gets pretty large. For 4x Deployment + 4x DiscoveryService it took more than 5 minutes to get ready (after that, I gave up and created them one by one)

**Comment by roivaz** [comment]
@pehala #174 modifies both the EnvoyDeployment and the DiscoveryService controllers to use a faster reconcile logic, so overall it should perform better now. The only remaining point that can cause slowness in both these controllers is the certificate generation, which is solely tied to the available cpu that the controller has. So if you still see reconcilliation being slow, it might be that cpu limit for the controller needs to be raised.

**Comment by pehala** [comment]
It is quicker than before, so I would call this resolved.
