### ISSUE TITLE
Update version in OperatorHub

### ISSUE THREAD

**Issue by pehala** [3scale-ops/marin3r#166]
It would be great if OperatorHub was kept up-to-date. Currently, it only contains 0.10.0 version (https://operatorhub.io/operator/marin3r)

**Comment by oarribas** [comment]
@roivaz , any updates on this? Currently, only 0.10.0 is available for the community operator.

**Comment by roivaz** [comment]
Hi @oarribas sorry it took so long. v0.13.1 is now available both in operatorhub.io and in the community catalog for Openshift.
