### ISSUE TITLE
Ability to load secrets other than of type `kubernetes.io/tls`?

### ISSUE THREAD

**Issue by GreenCappuccino** [3scale-ops/marin3r#218]
When using `envoy.extensions.filters.http.oauth2.v3.OAuth2`, `credentials.token_secret` and `credentials.hmac` secret are required, which don't fit into TLS Secrets. From what I can tell marin3r doesn't load non-TLS secrets, and I cannot specify `extraVolumeMounts` in `EnvoyDeployment` to work around this issue.

**Comment by GreenCappuccino** [comment]
Hello, thank you for responding

> I'm assuming that a generic secret is what's required for your use case, let me know if I'm wrong.

Interestingly the [OAuth2 Credentials](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#extensions-filters-http-oauth2-v3-oauth2credentials) take [SdsSecretConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/secret.proto#extensions-transport-sockets-tls-v3-sdssecretconfig), I think that that is a different resource? I think the `ads` and `api_config_source` fields of the `ConfigSource` on that should be of interest.

I think the most ideal solution would be to be able to create such secrets as you described in the second option, though I'm not entirely sure of what that entails for implementation.

`extraVolumeMounts` (also for the sidecar?) and `extraVolumes` could also potentially be useful as a stopgap and be useful beyond the scope of this issue, I'm not sure. But yes, it would just a workaround from not having a native secret solution in this case.

**Comment by roivaz** [comment]
Hi @GreenCappuccino, sorry for taking so long to reply. I've implemented the possibility of loading k8s opaque secrets into envoy generic secret protos (see https://github.com/3scale-ops/marin3r/pull/221). I have tested this with the oauth2 filter and seems to work fine. You can check the example in https://github.com/3scale-ops/marin3r/tree/feat/generic-secret/examples/k8s/oauth2.
If interested in trying it yourself, you can use the image `quay.io/3scale/marin3r:v0.13.0-alpha.2`, which contains the changes.

**Comment by roivaz** [comment]
This feature was release with v0.13.0

/close
