### ISSUE TITLE
Move CI to github actions

### ISSUE THREAD

**Issue by roivaz** [3scale-ops/marin3r#77]
We are in the process of moving all of our CIs from CircleCI to github actions.

**Comment by gsaslis** [comment]
Honest question: 

Why?

**Comment by roivaz** [comment]
We plan on using github actions in all of our repos. It's free for private repositories, not just for public ones, so it suits us as we have some repos that need to be private due to the nature of the info stored there.

Furthermore, I like the syntax much more, and the integration with the different events on the repository seems much more natural (reacting to PRs, tags, releases, etc). Of course this is just a matter of personal taste :)

**Comment by roivaz** [comment]
Closed with #86
